### ISSUE TITLE
What is the equivalent of IDiaSymbol::get_length?

### ISSUE THREAD

**Issue by pierricgimmig** [MolecularMatters/raw_pdb#3]
To get the length in bytes of a function from its corresponding DIA symbol, we can use the [`get_length`](https://docs.microsoft.com/is-is/visualstudio/debugger/debug-interface-access/idiasymbol-get-length?view=vs-2019) accessor. How could we retrieve the same information in raw_pdb?

**Comment by MolecularMatters** [comment]
Since you specifically asked about function symbols, I guess this is for Optick, so I assume you are only interested in function symbols per se.

The wastest way I know of how to do that would be the following:
1) Walk the module symbol streams first and fetch everything that is a function. Keep track of which RVAs you already found, this is neeed for later. The size of the function is stored in any of the S_*PROC.codeSize members.
2) At this point, you already know ~90% of all function symbols and are done. However, with stripped PDBs or certain PDBs from middleware providers, there will be public symbols that are not stored in any of the module streams.
3) Walk the public symbol stream, ignoring anything that is not a function. This can be done with a simple bit-check against S_PUB32.flags.
4) For each public symbol that is a function, consult the previously stored table of RVAs from step 1. If this is a new symbol, you still need to get its size. This can be done by matching the symbol's RVA against the contributions using either a binary search (the contributions are all sorted by RVA in the PDB), or using a hash map.

Since function symbols & sizes are what most profilers are interested in, I will provide an example for that.

**Comment by MolecularMatters** [comment]
I added an [example](https://github.com/MolecularMatters/raw_pdb/blob/13b2e7379c9b45baca30fa075470b31aabf10a55/src/Examples/ExampleFunctionSymbols.cpp) that demonstrates how to do this.
Let me know if that works for you.

**Comment by pierricgimmig** [comment]
Thanks a lot for the detailed example! I'll try it out today and let you know how it goes.

> Since you specifically asked about function symbols, I guess this is for Optick

It's for [Orbit](https://github.com/google/orbit) :-)

We already have two pdb parser implementations, one using LLVM and the other one using the DIA SDK. We're interested in seeing how raw_pdb compares.

**Comment by MolecularMatters** [comment]
> It's for [Orbit](https://github.com/google/orbit) :-)

Ah yes, I always mix up Orbit and Optick :).
I know Orbit from when you first presented it, it seems to have grown a lot during the last years!

**Comment by pierricgimmig** [comment]
Quick update on this. I integrated the sample code you provided and it seems to work as expected. The raw_pdb implementation is much faster than its DIA counterpart. It also found more symbols than both our DIA and LLVM versions, I need to dig a bit more to understand exactly what the difference is. I did notice quite a bit of "ILT" symbols which I'm discarding, but I still have more symbols than before, which is good but surprising. It's probably the "public symbols that are not stored in any of the module streams". Many thanks @MolecularMatters for your help and for the great project!

**Comment by pierricgimmig** [comment]
Again, thanks @MolecularMatters for the detailed answer. This is great information, I'll double check our Llvm and Dia implementations.

**Comment by pierricgimmig** [comment]
> It would be great if you could provide some numbers for comparison, once you figure out which symbols you are missing in DIA.

Absolutely!!

**Comment by florian-kuebler** [comment]
>However, what you might be missing is the fact that with DIA, you have to recurse into returned IDiaSymbol* with ::findChildren. If you don't do that, you will certainly be missing symbols.

Is this only true when iterating over the different compilads/modules and their children (with the filter for SymTagFunction), or do I also need to do take care of this when getting all children (that have SymTagFunction) from the global scope, right away?

In my experiments, the results were the same.

>enumerate all SymTagFunction and SymTagBlock (!)

Also, as far as I understand the documentation, blocks should usually not have a name, and there should be a function surrounding them, right? So for Orbit, it would be fine to ignore those.

**Comment by MolecularMatters** [comment]
> Is this only true when iterating over the different compilads/modules and their children (with the filter for SymTagFunction), or do I also need to do take care of this when getting all children (that have SymTagFunction) from the global scope, right away?
> 
> In my experiments, the results were the same.

If I remember correctly, Clang likes to store data symbols as children of the global scope sometimes (e,g, function static variables), which MSVC never does.

> Also, as far as I understand the documentation, blocks should usually not have a name, and there should be a function surrounding them, right? So for Orbit, it would be fine to ignore those.

I think that is mostly true, but I encountered blocks that don't seem to belong to any other function, and had to be matched against address ranges from other function symbols. That only seemed to be the case for certain kernel symbol PDBs though.
Maybe @rovarma from Superluminal can comment, since I believe he also ran into this.

**Comment by florian-kuebler** [comment]
>If I remember correctly, Clang likes to store data symbols as children of the global scope sometimes (e,g, function static variables), which MSVC never does.

As I was only looking into function symbols and not data symbols, that seem to be fine. Thanks for the explanation!

>I think that is mostly true, but I encountered blocks that don't seem to belong to any other function, and had to be matched against address ranges from other function symbols. That only seemed to be the case for certain kernel symbol PDBs though.

Thanks for the clarification. If you remember the pdbs in question, that would be great.
