### ISSUE TITLE
How to get type size

### ISSUE THREAD

**Issue by 852781703** [MolecularMatters/raw_pdb#41]
example:
	unsigned __int64 get_size(const wchar_t* name)
	{
		unsigned __int64 uSize = 0;
		do {
			constexpr auto k_size = sizeof(SYMBOL_INFOW) + MAX_SYM_NAME * sizeof(wchar_t);
			unsigned char buf[k_size]{};
			auto info = reinterpret_cast<SYMBOL_INFOW*>(buf);
			info->SizeOfStruct = k_size;
			info->MaxNameLen = MAX_SYM_NAME;
			if (SymGetTypeFromNameW(m_process_handle, m_symbol_base, name, info) == false)
				break;
			SymGetTypeInfo(m_process_handle, m_symbol_base, info->TypeIndex, TI_GET_LENGTH, &uSize);
		} while (false);
		return uSize;
	};

**Comment by MolecularMatters** [comment]
Since RawPDB gives you access to the underlying streams and this is considered a high-level function, you need to grab the types from the TPI stream yourself and e.g. build a lookup-table/hashmap into that.

This ExampleTypes (https://github.com/MolecularMatters/raw_pdb/blob/main/src/Examples/ExampleTypes.cpp ) should be a good start.
