### ISSUE TITLE
Why do you not parse line information?

### ISSUE THREAD

**Issue by Vasil-Kirov** [MolecularMatters/raw_pdb#5]
It seems fairly critical to me, if someone is making a debugger or anything like that.

**Comment by MolecularMatters** [comment]
I stated this in the README, but you might have missed that:
> At the moment, there is no support for C13 line information and the TPI type stream data, because Live++ does not make use of that information yet.

As you said, line information and type symbols are crucial for a debugger, but they aren't implemented (yet) because we didn't have a need for them.
We already know where line information is stored (in the module streams, see [https://llvm.org/docs/PDB/ModiStream.html]), but we don't provide a data structure for parsing that yet.

Can you point us to information how C13 line information is structured? We might add support for it ourselves, depending on how much work it's going to be.

**Comment by Vasil-Kirov** [comment]
Sorry for missing that part of the read. I've been trying to find out the structure of line information for a while and have found next to nothing. In the microsoft-pdb github repo in file mod.cpp there is a function `Mod1::GetC11LinesFromC13(Buffer& bufC11Lines)` that seems to be the where they parse line information, however their code is extremely hard to read and I can't even find definitions for some of the methods and classes being used there so I haven't been able to actually find out how the information is structured. Anyway I hope this helps, thanks for your time.

**Comment by MolecularMatters** [comment]
No need to apologize.
It seems that the [Rust PDB crate](https://github.com/willglynn/pdb/blob/master/src/modi/c13.rs) has full support for C13 line information, but by the looks of it, it's another set of complicated data streams in an already complicated format, so it looks like a more time-consuming task.

**Comment by MolecularMatters** [comment]
@Vasil-Kirov Just wanted to let you know that @lukekasz added support for C13 line information to the library, thought you might be interested in that.
