### ISSUE TITLE
ExampleTypes assert in DisplayFields()

### ISSUE THREAD

**Issue by graemekelly** [MolecularMatters/raw_pdb#59]
This code asserts:

```
#include <fstream>

namespace
{
	struct empty : std::ifstream
	{
		empty() {}
	};
}

int main()
{
	return 0;
}
```

Due to no support for LF_IVBCLASS. If you change the struct to a class, works fine.

From what I can tell here with this limited test case, replicating https://github.com/microsoft/microsoft-pdb/blob/master/include/cvinfo.h#L2521 seems like it works, but I am not quite sure that's the whole picture. I haven't had any luck in narrow down a more representative test case from what I'm getting when running across our codebase here, so figured it best to just post an issue to see what you thought.

**Comment by MolecularMatters** [comment]
All the examples that deal with the TPI (type information) stream are not fully complete yet.
Loading the TPI stream works, but it is up to the user code (the example) to interpret the data correctly.

Since there are a ton of different types, not all of them are understood yet and the code will simply assert.
Should be issue to add support for LF_IVBCLASS, since its layout is documented in the MS repo you linked to.

**Comment by lukekasz** [comment]
Turns out this LF_IVBCLASS issue also needed to be fixed for the examples to be able to run on the chrome.dll.pdb in issue https://github.com/MolecularMatters/raw_pdb/issues/32

The changes are on this branch:

https://github.com/lukekasz/raw_pdb/tree/chrome-dll-pdb-fixes

I will open a PR once with the changes once I've done some additional testing on others PDBs. Feel free to test it yourself :-)

**Comment by graemekelly** [comment]
Yeah, that branch works fine for my test case here.

**Comment by MolecularMatters** [comment]
This issue should be resolved due to the recent changes/fixes.
