### ISSUE TITLE
Can a pdb file be modified？

### ISSUE THREAD

**Issue by GuBuChang** [MolecularMatters/raw_pdb#74]
just a question

a lot of repo tell me how read a .pdb file.
can we modify a .pdb file and make msbuild work successful?

Just to name one example.
if i modify a .obj path in .pdb file, can we be allowed?

**Comment by MolecularMatters** [comment]
Due to the underlying structure of a PDB file (MSF streams), modifying an existing PDB is hard and you're probably better off producing a new PDB instead.
Many of the offsets inside the streams could change if you were to modify just a single filename, depending on where you want to make the change.

Modifying an .obj path without changing its length should be fine though.

**Comment by GuBuChang** [comment]
get it.
